services:
  frontend:
    build: ./frontend/
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - web

  backend:
    build: ./go_backend/
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
    networks:
      - web
      - db
  
  processor:
    build: ./python_processor/
    depends_on:
      redis:
        condition: service_started
    networks:
      - db

  postgres:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - db

  redis:
    image: redis:7.4
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - db

volumes:
  postgres_data:
  redis_data:

networks:
  web:
  db: